### ISSUE TITLE
如何手动暂停继续下载任务？

### ISSUE THREAD

**Issue by heaton0308** [yjfnypeu/UpdatePlugin#10]
非强制更新下，建议添加notification显示下载进度，及手动暂停继续更新功能，强制更新下下载对话框不可取消

**Comment by yjfnypeu** [comment]
暂时不准备添加暂停继续下载功能以及notifacation。因为这些功能并非是所有人都需要的。如果有需要。可以自己定制下载任务实现暂停下载。下载时需要显示Notification可以定制DownloadCreator，在创建返回的DownloadCB回调中去更新Notification。
