### ISSUE TITLE
当强制更新时，对话框返回为空时会crash

### ISSUE THREAD

**Issue by CheersCrazy2** [yjfnypeu/UpdatePlugin#11]
问题：强制更新，对话框返回空时会crash

场景：在使用自定义对话框时，需要返回一个dialog，这时候业务需要，需要在dialog里面点击按钮时需要处理业务逻辑，所以有时候需要返回dialog=null。这时候如果强制更新会crash

解决办法：在DefaultCheckCB类中多加一个判空条件。
 Dialog dialog = creator.create(update, actRef.get());
        if (update.isForced() && dialog != null) {
            dialog.setCanceledOnTouchOutside(false);
            dialog.setCancelable(false);
        }

**Comment by yjfnypeu** [comment]
这个可以在下个版本加上。只是没理解需要点击按钮处理自己的业务逻辑与需要返回dialog=null有啥关联呢？

**Comment by yjfnypeu** [comment]
dialog为null的判断已加上。更新版本号为0.5即可。

**Comment by CheersCrazy2** [comment]
没理解业务就对了，我到现在也不理解那个傻逼产品出这些需求~

**Comment by yjfnypeu** [comment]
嗯。新版本已解决此问题。
