### ISSUE TITLE
正好项目用到，膜拜大神

### ISSUE THREAD

**Issue by senlinxuefeng** [yjfnypeu/UpdatePlugin#13]
我们公司在网络请求的时候加入特定的请求头，有点不是很方便，修改了源码搞定了，谢谢

**Comment by yjfnypeu** [comment]
嗯。多谢支持。这几天会找时间写个如果对框架各个模块进行定制的Sample示例。到时候会写如果需要加入请求头应该怎么去修改定制的。不需要修改源码的
