### ISSUE TITLE
进度条不显示

### ISSUE THREAD

**Issue by WangPney** [yjfnypeu/UpdatePlugin#15]
用的自定义策略弹出框的那个，进度条不显示，打了断点进入发现total参数为-1  不知道啊为何  求大神指教

**Comment by yjfnypeu** [comment]
total参数为-1说明这个文件下载接口有问题。没有返回Content-Length头。可以找服务器问问。

**Comment by WangPney** [comment]
恩恩 谢谢大神~~~~~
