### ISSUE TITLE
请问这个有没有实现 ：不更新就退出app或者不能使用app的功能？

### ISSUE THREAD

**Issue by s1168805219** [yjfnypeu/UpdatePlugin#17]
请问这个有没有实现这个功能：不更新就退出app或者不能使用app的功能？

**Comment by yjfnypeu** [comment]
这是强制更新的功能。框架的默认实现在强制更新下会取消不了更新提示对话框，只能更新。如果你觉得不符合你的要求也可以自己去定制出这种功能的
