### ISSUE TITLE
下载进度条不更新进度

### ISSUE THREAD

**Issue by hanyifenghuo** [yjfnypeu/UpdatePlugin#18]
你好，很高兴有这个框架，我在使用中遇到一个问题
下面代码我设置了true  
@Override
public boolean isShowDownloadDialog() {
                return true;
 }

下载进度条显示了，但是进度不更新，一直为0，下载完成后结束

需要设置什么才能显示进度，还是跟某个策略冲突了？

**Comment by yjfnypeu** [comment]
策略之间都是独立的，没有冲突的。你试试添加下载回调监听，看是否有进度条通知。使用setDoweloadCB看看。
