### ISSUE TITLE
0.7.1版本的original 是什么意思？

### ISSUE THREAD

**Issue by beiliubei** [yjfnypeu/UpdatePlugin#19]

**Comment by yjfnypeu** [comment]
你是指的Update类中的吧？original代表接口原始数据。框架内部并没有使用。主要是为了给部分定制用户提供对于框架本身数据还不够满足要求的情况做个兼容。如果没有此类需要可以忽略它

**Comment by chengchao156** [comment]
如果直接设置original的值为空值也没有关系吧

**Comment by yjfnypeu** [comment]
嗯，没关系的。
