### ISSUE TITLE
UpdateWorker怎么替换成自己异步请求

### ISSUE THREAD

**Issue by cccdada** [yjfnypeu/UpdatePlugin#20]
作者，您好，谢谢提供者这么好的通用的更新组件，这里我有一个疑问，我尝试继承UpdateWorker在check中调用自己项目中的异步请求，但是不得法，我注意到文档中有写check是在子线程中，请问这里有什么好的思路吗？

**Comment by yjfnypeu** [comment]
呃。老实说。我没考虑过定制网络任务时使用异步操作的。因为一般来说网络框架都是应该兼容到可以选择使用同步或者异步请求的功能的。所以如果能做到让网络层本身就能同步请求是最好。如果实在没办法。可以考虑讲异步模拟为同步的操作。不如加入一个可阻塞的队列。让数据没请求回来的时候阻塞线程也行。

**Comment by cccdada** [comment]
好的，谢谢耐心回答。以前习惯异步请求，用的别人的简陋的请求框架，我这里也准备换网络框架了，同步请求就不是问题了。
