### ISSUE TITLE
DownloadWorker下载apk的地方，每次都写本地数据，导致下载测度受很大影响。建议优化下。

### ISSUE THREAD

**Issue by triplezhao** [yjfnypeu/UpdatePlugin#22]
while ((length = inputStream.read(buffer)) != -1) {
            raf.write(buffer, 0, length);
            offset += length;
            UpdatePreference.saveDownloadSize(url,offset);//这里效率低
            long end = System.currentTimeMillis();
            if (end - start > 1000) {
                sendUpdateProgress(offset,contentLength);
            }
        }

目前可以复写DownloadWorker来解决这个问题。但是还是想提醒下作者。

**Comment by yjfnypeu** [comment]
嗯。这里的确会容易有性能问题。之前没注意到这里，多谢指出。

**Comment by yjfnypeu** [comment]
已更新新版本0.9。优化了此问题。
