### ISSUE TITLE
在android7.0版本更新下载完成之后安装会崩溃

### ISSUE THREAD

**Issue by love-311** [yjfnypeu/UpdatePlugin#23]
![image](https://cloud.githubusercontent.com/assets/19263806/21513346/44527196-ccf2-11e6-8bdf-5591cf65ea17.png)

**Comment by yjfnypeu** [comment]
这是Android N的新特性导致的。一直想修复但是一直没有相应的测试环境来进行测试修复。多谢提供错误反馈。我会尽快找到修复办法

**Comment by love-311** [comment]
非常棒的更新库，这里提个建议就是可以继续封装一个通知栏更新APP，而不是在APP界面上显示更新进度，这也是当前大多数APP的大势所趋。。

**Comment by yjfnypeu** [comment]
通知栏更新的需求可以通过对下载进度进行定制来做到的。。。因为需要尽量避免库的体积太大。所以库中默认使用的都只有一个。后期可以考虑在sample中加入各种定制好的组件来使用。。。不过建议最好还是了解下对各个模块的定制方式。这样也能更好的做到自己需要的效果

**Comment by love-311** [comment]
是滴，说得非常的在理。。(*^__^*)

**Comment by yjfnypeu** [comment]
新版本已上传上去了。解决好了7.0的安装问题。你改版本号为1.0试试吧

**Comment by love-311** [comment]
早上来自己正好改了就看到你的邮件了。。O(∩_∩)O哈哈~另外提交一个逻辑上的错误就是在已经下载了安装包的情况下，如果第一次没有安装第二次进去就会再次提醒下载更新，其实逻辑上已经是走的免下载安装了，提示有一些问题，如果有安装包了应该提示免下载安装。。

**Comment by yjfnypeu** [comment]
这应该算不上逻辑上的错误。因为每一次的更新都是走的全流程。不能说我之前已经下载过了。然后我就不用再次检查是否是应该直接不访问更新接口检查新版本更新了。只能是你之前已经下载完了。后面再次更新的时候。下载时校验好文件完整性。就不用再次下载了。当然对于你这种情况。建议可以定制一个策略类做控制。也能达到同样的效果

**Comment by love-311** [comment]
逻辑上我觉得是没问题的，只是在提示给用户的感觉上是有一些问题的，因为已经下载好你要更新的包的情况下，就应该提示为免下载更新而不是下载更新。。不知你是否赞同这点。。

**Comment by yjfnypeu** [comment]
嗯。对的。所以建议是根据你的具体情况定制一个策略类UpdateStratety做控制。就能达到同样的效果。

**Comment by naitcn** [comment]
雁过留声
