### ISSUE TITLE
希望增加通知栏显示下载进度的功能

### ISSUE THREAD

**Issue by Leu-Z** [yjfnypeu/UpdatePlugin#26]
现在框架只有弹出框中显示现在进度的功能，对用户体验不是很好，希望增加通知栏显示下载进度的功能，用户可以变使用应用边下载。所谓的静默下载安装

**Comment by yjfnypeu** [comment]
框架提供了各种的定制功能。你可以自己定制一个下载时的进度通知出来使用。毕竟通知栏更新的功能并不是所有人都需要使用的。不能直接放到框架中去。请理解

**Comment by yjfnypeu** [comment]
静默安装是通过定制更新策略类来做实现的。你可以通过定制一个你自己需要的策略类。来规避前台消息通知显示。达到静默安装的效果。

**Comment by Leu-Z** [comment]
感谢你的建议😊

**Comment by yjfnypeu** [comment]
刚更新了一下示例代码。加入了一个简单定制通知栏显示下载进度的功能。你可以看看然后进行一定修改以更适应你们项目使用
