### ISSUE TITLE
扩展性不是很好

### ISSUE THREAD

**Issue by flsyfish** [yjfnypeu/UpdatePlugin#27]
希望能放开写东西 ，比如说自定义的弹窗 和返回的实体

**Comment by yjfnypeu** [comment]
你可以仔细查看一下项目[wiki](https://github.com/yjfnypeu/UpdatePlugin/wiki),里面有说明各种接口扩展说明

**Comment by flsyfish** [comment]
private static OkHttpClient sOkClient;

    @Override
    protected String check(CheckEntity entity) throws Exception {
        // 自定网络任务。在此通过同步请求的方式调用即可
        Request.Builder builder = new Request.Builder().url(entity.getUrl());
        if (HttpMethod.GET.equals(entity.getMethod())) {
            builder.method("GET",null);
        } else {
            FormBody.Builder bodyBuilder = new FormBody.Builder();
            Map<String, String> params = entity.getParams();
            if (params == null) {
                params = new HashMap<>();
            }
            Set<String> keys = params.keySet();
            for (String key : keys) {
                bodyBuilder.add(key,params.get(key));
            }
            builder.method("POST",bodyBuilder.build());
        }
        Request request = builder.build();

        Call call = sOkClient.newCall(request);
        return call.execute().body().string();
    }

    static {
        HttpsUtils.SSLParams sslParams = HttpsUtils.getSslSocketFactory(null, null, null);
        sOkClient = new OkHttpClient();
    }

你好我想问下 加自定义的证书要在那个地方加

**Comment by yjfnypeu** [comment]
你可以通过定制网络层来实现，也就是将框架使用的网络层使用你们应用本身的网络层来替换使用即可。

**Comment by flsyfish** [comment]
你好，我想请教下，只需要下载的功能改怎么使用@ @yjfnypeu

**Comment by yjfnypeu** [comment]
可以参考[APK下载网络任务](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9AAPK%E4%B8%8B%E8%BD%BD%E7%BD%91%E7%BB%9C%E4%BB%BB%E5%8A%A1)这篇wiki

**Comment by flsyfish** [comment]
@yjfnypeu  好的，谢谢
