### ISSUE TITLE
2.0最新版本在安卓7.0系统中下载apk后安装报错，Writing exception to parcel

### ISSUE THREAD

**Issue by androidZhai** [yjfnypeu/UpdatePlugin#28]
手机是Nexus 5.0 ，系统是安卓7.0
E/DatabaseUtils: Writing exception to parcel
java.lang.IllegalArgumentException: Unable to find configured root for content://com.baowei.wwb.provider/storage/emulated/0/WWB/wwb_2.2.0.apk
at android.support.v4.content.FileProvider$SimplePathStrategy.getFileForUri(FileProvider.java:739)

**Comment by yjfnypeu** [comment]
框架本身并没有使用FileProvider。所以请检查一下你是在什么地方有使用到FileProvider。
