### ISSUE TITLE
好多BUG

### ISSUE THREAD

**Issue by xiangping5211** [yjfnypeu/UpdatePlugin#3]
应该是GET的请求，但是代码里设置了setDoOutput(true)，变成POST请求了

**Comment by yjfnypeu** [comment]
这个问题已经修改过了。现在找工作中所以暂时还没办法把新版发出来。可以将现在最新的DefaultDownloadWorker类复制出来放入项目中。再通过UpdateConfig类设置一下进行默认下载任务定制。

**Comment by xiangping5211** [comment]
嗯，已经在项目中使用了，非常好用，谢谢
