### ISSUE TITLE
还可以新增一些策略

### ISSUE THREAD

**Issue by chenyang1900** [yjfnypeu/UpdatePlugin#30]
还可以新增一些策略：  
1.root机    在wifi下静默安装 ，有漏洞就要钻 。
2.非root 机  
  （1）对非强制需求 每天只第一次启动应用显示更新对话框 ，其他时间不弹出更新信息防止每次启动应用都弹出更新信息。
  在移动4G下提示是否下载 ，取消后不进行任何后台操作 。
  在wifi下取消了更新 ，也在后台偷偷进行下载，下载完成不提示直接安装 。
   每次下载时先查看存放app下载的包是否存在最新包 ，存在直接intent启动安装 ，安装完成后删除安装包,避免多次下载。
 (2) 对于强制更新 屏幕中显示一个进度框 不能返回不能进行任何操作。
 同时感觉强制更新这个体验非常不好 ，有个想法：在接口返回那个参数里面添加一个是否强制更新的字段和是否及时更新的字段 。学那些大厂的app ，先提前下载到文件夹下 。等到一个过约定的时间 ，打开开始提醒强制更新 。这样避免所有的用户都要实时的更新。

**Comment by yjfnypeu** [comment]
多谢指出。会好好考虑

**Comment by yjfnypeu** [comment]
不好意思。最近事有点多。更新不太及时。

根据你的建议。刚更新了2.3.0版本。添加了[FileChecker](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E5%AE%89%E8%A3%85%E5%8C%85%E6%A3%80%E6%9F%A5%E6%8E%A5%E5%8F%A3)接口，希望能够满足你的需求。

具体可以看看[更新日志](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)

**Comment by yjfnypeu** [comment]
然后对于root环境静默安装。暂时没发现此功能的必要性。

然后强制更新，update中本身即有此字段。对于强制更新时Dialog不能返回。这个需要你自己定制各个时机的Dialog时根据update中的forced字段进行定制。框架本身的几个Dialog都是有做过强制更新的适配的。

**Comment by chenyang1900** [comment]
恩 看到了，自己你的流程做到非常棒 。地基都给我们打好了，省了很多事 。接下来就是我们根据实际需求完善我们需要的 。
