### ISSUE TITLE
自定义的原生dialog无法弹框

### ISSUE THREAD

**Issue by is1988** [yjfnypeu/UpdatePlugin#32]
应用第一次打开可以正常调接口获取更新内容并弹框
在主页面点击home键再进来也可以正常调用接口并弹框
但是进入二级页面再返回主页就只能正常调用接口无法弹框了

我的逻辑是在onResume里写的  请问哪里出问题了吗

**Comment by yjfnypeu** [comment]
你可以设置个回调监听器看看回调的信息是什么。来判断具体是什么地方的问题。

**Comment by is1988** [comment]
请问回调监听是checkCB(new UpdateCheckCB() )吗? 我在hasUpdate里都可以看到update的更新内容，并且CustomNeedUpdateCreator也走到了最后一步return dialog; 但就是不弹框，以上不弹出的行为就只有点击二级页面返回不显示，而点击home再进来就正常，无论代码写道onResume还是onRestart都是如此，还请大神指点一二。

**Comment by is1988** [comment]
```
    public static void update() {
        UpdateBuilder builder = UpdateBuilder.create();
        builder.strategy(new AllDialogShowStrategy()); // wifi 环境下显示下载对话框 （默认不显示）
        builder.updateDialogCreator(new CustomNeedUpdateCreator()); // 检查更新对话框
        builder.installDialogCreator(new CustomNeedInstallCreator()); // 安装更新对话框
        builder.downloadDialogCreator(new CustomNeedDownloadCreator()); // 下载对话框
        builder.check();
    }
```
这是设置弹出框的代码

**Comment by yjfnypeu** [comment]
@is1988 回调监听有两个。一个就是checkCB。这个是检查更新时的通知。一个是downloadCB。这个是检查到有更新进行下载时的回调通知。这两个主要用来让你方便定位问题的。然后照你的描述，你应该是用的之前的老版本的，推荐你更新到最新的版本。应该就没这问题了。

**Comment by is1988** [comment]
现在用的应该是最新版2.4的
    // 版本更新
    compile 'org.lzh.nonview.updateplugin:UpdatePlugin:2.4'

**Comment by is1988** [comment]
或许是我的逻辑有问题，应该是有更好的办法可以实现更新机制。  但这个bug 实在是想不通

**Comment by yjfnypeu** [comment]
我也有点懵。因为新版本是内部用于加载展示各种界面的时候。都是使用的当前最顶层的Activity用作展示。你可以跟一下DefaultCheckCB类的hasUpdate方法。看看是不是当前的使用的Activity用来展示不成功导致的？

**Comment by maweilong** [comment]
同问 请问解决了么

**Comment by yjfnypeu** [comment]
@maweilong 我这里没复现出问题。你的具体问题是怎样的?

**Comment by maweilong** [comment]
是我搞错了
