### ISSUE TITLE
更新的url没有设置head的方法

### ISSUE THREAD

**Issue by pomforandroid** [yjfnypeu/UpdatePlugin#33]
需要设置head，发现没有这个方法

**Comment by yjfnypeu** [comment]
框架本身所使用的网络层并没有提供head支持的功能。可以考虑通过定制网络层来实现。
[配置：检查更新接口网络任务](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E6%A3%80%E6%9F%A5%E6%9B%B4%E6%96%B0%E6%8E%A5%E5%8F%A3%E7%BD%91%E7%BB%9C%E4%BB%BB%E5%8A%A1)
