### ISSUE TITLE
有关安装的问题

### ISSUE THREAD

**Issue by Troll4it** [yjfnypeu/UpdatePlugin#34]
您好，当我下载成功后，但是安装失败后，再一次启动app就不会启动弹窗。现在我需要的效果就是安装失败后还是能弹出更新的弹窗

**Comment by yjfnypeu** [comment]
你是指的跳转安装页面安装失败？这种我暂时没找到好的方式去监听安装状态。所以还没支持

**Comment by Troll4it** [comment]
对对，因为我刚测试的时候服务器放的是一张图片的地址，肯定会出现安装失败。。。希望大佬早些更新支持

**Comment by yjfnypeu** [comment]
@Troll4it 我这边测试了网上提供的一些方法。均不能有效的对跳转到安装页面有的操作做监听。或者如果你有好的方式做安装操作。可以继承InstallCreator。通过复写sendToInstall方法来做替换请求升级安装应用的操作。由自己去定制这块的操作。

**Comment by Troll4it** [comment]
好的，谢谢提供思路
