### ISSUE TITLE
下载任务可以暂停吗

### ISSUE THREAD

**Issue by ws123** [yjfnypeu/UpdatePlugin#35]
比如，刚开始下载的时候，是WIFI，后来切换到了4G，需要暂停下载任务，然后，通知用户是否继续下载

**Comment by yjfnypeu** [comment]
框架本身并没有提供此功能。如果你需要使用的话。可以考虑将发起任务的UpdateBuilder类以及更新数据实体类Update做缓存。然后在需要重新下载的时候。通过Updater.downUpdate(update, builder)方法直接重新发起下载请求。
