### ISSUE TITLE
检查App完整性问题

### ISSUE THREAD

**Issue by a2open** [yjfnypeu/UpdatePlugin#36]
在弹出更新对话框前，能否得之前是否已经下载好App？我的想法是：用户点击版本检查时，如果得知App已经下载好，直接在更新对话框提示用户免流量更新。

**Comment by yjfnypeu** [comment]
这个功能是有的。你可以看看wiki的[配置：安装包检查接口](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E5%AE%89%E8%A3%85%E5%8C%85%E6%A3%80%E6%9F%A5%E6%8E%A5%E5%8F%A3)
