### ISSUE TITLE
自定义提示对话框和下载对话框

### ISSUE THREAD

**Issue by lubowen1990** [yjfnypeu/UpdatePlugin#37]
支持自定义提示对话框和下载对话框吗？是不是只能在本地lib库中更改？

**Comment by yjfnypeu** [comment]
@lubowen1990 这些都是支持的。你可以参考wiki：

1. [配置：检查到有更新时的通知](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E6%A3%80%E6%9F%A5%E5%88%B0%E6%9C%89%E6%9B%B4%E6%96%B0%E6%97%B6%E7%9A%84%E9%80%9A%E7%9F%A5)

2. [配置：APK下载进度通知](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9AAPK%E4%B8%8B%E8%BD%BD%E8%BF%9B%E5%BA%A6%E9%80%9A%E7%9F%A5)

3. [配置：下载完成安装前通知](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E4%B8%8B%E8%BD%BD%E5%AE%8C%E6%88%90%E5%AE%89%E8%A3%85%E5%89%8D%E9%80%9A%E7%9F%A5)

wiki右侧列出了所有框架支持定制的接口。建议可以好好查看一下。
