### ISSUE TITLE
如果请求更新的接口出问题了，比如说网络异常啊，接口发生了改动找不到服务器啊什么的。有没有异常回调啊？

### ISSUE THREAD

**Issue by cxrenbin** [yjfnypeu/UpdatePlugin#38]

**Comment by yjfnypeu** [comment]
都是有的。你可以看看[更新配置说明](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)进行整体流程的了解。或者你只需要回调的话。可以看下面两个接口：

- [检查更新接口回调通知](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E6%A3%80%E6%9F%A5%E6%9B%B4%E6%96%B0%E6%8E%A5%E5%8F%A3%E5%9B%9E%E8%B0%83%E9%80%9A%E7%9F%A5)
- [APK下载回调监听](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9AAPK%E4%B8%8B%E8%BD%BD%E5%9B%9E%E8%B0%83%E7%9B%91%E5%90%AC)

**Comment by cxrenbin** [comment]
好的。非常感谢
