### ISSUE TITLE
url为post请求时怎么传入map

### ISSUE THREAD

**Issue by chenwulue** [yjfnypeu/UpdatePlugin#4]
为post请求了，请求参数怎么配置呢？

**Comment by yjfnypeu** [comment]
你可以自己定制下载任务的。继承DownloadWorker类。在里面根据你的api请求数据并然后将其设置到config中就行了

**Comment by chenwulue** [comment]
不是下载的，是访问版本信息接口的url

**Comment by yjfnypeu** [comment]
访问版本信息接口也可以定制，实现UpdateWorker。并用UpdateConfig配置就行了。

**Comment by chenwulue** [comment]
明白了，抱歉我没仔细看文档。 现在看看能不能整合到我的app里去，我的是自己通过ApplicationContext打开一个自动更新的页面的，那里没有传Activity，琢磨琢磨先

**Comment by yjfnypeu** [comment]
新的0.5版本加入了更新接口的post请求。只需要将UpdateConfig的url方法替换为checkEntity即可。checkEntity即可指定访问方式以及url params
