### ISSUE TITLE
还有一个关于强制更新的改进建议

### ISSUE THREAD

**Issue by Jvr0771** [yjfnypeu/UpdatePlugin#40]
有这样的场景：刚刚上线的版本有重大bug，现在紧急上线一个新版，需要强制用户下载新版本安装后才能继续使用app.对于要强制更新的版本，在点击下载后，应该在当前Activity弹窗显示下载进度，不给用户往下使用app了

**Comment by yjfnypeu** [comment]
框架本身就有提供强制更新逻辑：Update数据类中有forced参数。就是代表是否为强制更新的，然后对于这个forced的逻辑处理。默认的几个弹窗都有对应的处理操作。如果你使用的就是框架本身提供的弹窗通知就没问题，如果你有自己定制这块逻辑。则可以参考默认提供的实现。

**Comment by Jvr0771** [comment]
嗯，我的意思是，如果Update数据类中有forced的值为真时，应该忽略对以下的逻辑有冲突的配置或策略：如果需要强制更新，提示更新的弹窗的按钮就只有“更新”这一个按钮，这样用户只能选择更新新版本。剩下的流程，为了避免用户钻空子，在下载完成后，需要用户点击安装按钮，确认安装新版本（当然，也可以自动跳转到app安装页面），然而，如果用户在app安装页面没有继续安装，选择回退，回到我们的app页面的时候，要重新弹窗引导用户完成安装。不然达不到强制用户安装新版本的目的。这也是不得已的流氓手段。

**Comment by yjfnypeu** [comment]
有道理。将在下版本中加入此逻辑控制功能。

**Comment by Jvr0771** [comment]
辛苦了。现在着急上线，先偷懒把检测更新卸载Activity的onResume方法里，这样用户在安装页面取消安装后回到Activity后可以重新走一次流程。

**Comment by yjfnypeu** [comment]
嗯。其实可以考虑在调起安装任务时，判断是否是强制更新。是强制更新就让强制退出应用。因为自身的安装状态是监听不到的。下版本的强制更新安装逻辑我也是准备的使用这种方式来做的。如果不强制退出的话。应该还有别的空子可以钻的

**Comment by Jvr0771** [comment]
简单，粗暴，有效。哈哈

**Comment by yjfnypeu** [comment]
@Jvr0771 强制更新逻辑已修改发布。可以参考一下[2.5.0发版日志。](https://github.com/yjfnypeu/UpdatePlugin/releases/tag/2.5.0)

**Comment by Jvr0771** [comment]
刚刚跑了下，调起安装任务时没有杀掉app呢，是代码漏提交了还是要我们自己实现呢？

**Comment by yjfnypeu** [comment]
呃。。。你看看是否依赖改成了JitPack仓库地址呢？或者你看看InstallCreator这个类的sendToInstall方法。在这里我是在安装后根据是否是强制更新。使用System.exit(0)强制关闭进程了。你看看有没这块代码呢？

**Comment by Jvr0771** [comment]
compile "com.github.yjfnypeu:UpdatePlugin:2.5.0"

早上改了，真没效果，难道还有在哪里需要配置？刚刚还看你在InstallCreator里加了个双保险

**Comment by yjfnypeu** [comment]
嗯。因为刚发现System.exit(0)这个退出方法在有些时候会失效。所以直接是使用Process.killProcess和System.exit(0)一起用。你那问题应该就是失效造成的。因为我本地测试其实是没问题的。不知道你对这块有了解么？或者能不能提点建议呢？

**Comment by Jvr0771** [comment]
直接gradle依赖的话不得，刚刚跑了demo,demo是可以的，不过在检查版本的接口返回的httpResponse解析方法里update.setForced(true);不管用，而且我居然找不到它在哪里被赋值未false，为了看强制更新效果，我只好在Update类里isForce()方法直接返回true

**Comment by yjfnypeu** [comment]
你更新版本号到2.5.1再试试。这个我把强制更新时强制退出逻辑放到了默认的安装策略DefaultInstallStrategy中去了。如果还不行就需要通过自己定制安装策略来实现了。

**Comment by Jvr0771** [comment]
2.5.1，可以了，辛苦了

**Comment by yjfnypeu** [comment]
客气~
