### ISSUE TITLE
我能自定义自己网络吗

### ISSUE THREAD

**Issue by Troll4it** [yjfnypeu/UpdatePlugin#41]

**Comment by Troll4it** [comment]
我的接口跟你不一样

**Comment by yjfnypeu** [comment]
可以，你可以参考wiki中的这两篇配置做定制：
- [检查更新接口网络任务](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E6%A3%80%E6%9F%A5%E6%9B%B4%E6%96%B0%E6%8E%A5%E5%8F%A3%E7%BD%91%E7%BB%9C%E4%BB%BB%E5%8A%A1)
- [APK下载网络任务](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9AAPK%E4%B8%8B%E8%BD%BD%E7%BD%91%E7%BB%9C%E4%BB%BB%E5%8A%A1)

更多的可配置项可以参考wiki中的配置说明进行了解
