### ISSUE TITLE
建议提供网络模块的灵活性

### ISSUE THREAD

**Issue by vecharm** [yjfnypeu/UpdatePlugin#42]
参数什么都填好，发现没反应，最后发现是我的服务器是使用https
瞎折腾了一会，发现封装的很死。无从配置。
UpdateWorker 虽然可以继承，但是却不是回调式。而我使用的是Okhttp 两个在不同的线程。 这很尴尬。
建议把
  private DefaultCheckCB checkCB;
  private UpdateBuilder builder;  改成protected 
sendHasUpdate，sendNoUpdate，sendOnErrorMsg，setRunning 也改成protected 会比较灵活些。不然没法搞

**Comment by yjfnypeu** [comment]
你直接使用Okhttp通过同步的方式请求数据就行了。为什么还需要操作那些回调？

**Comment by vecharm** [comment]
因为我这边也封装的很死，没事了，我已经让SDK开发人员提供了一个接口方法
