### ISSUE TITLE
强制更新时闪退问题？

### ISSUE THREAD

**Issue by luoximin1990** [yjfnypeu/UpdatePlugin#43]
测试时把强制更新属性默认设置为true；程序安装时立马闪退！！！
定位如下：
![image](https://user-images.githubusercontent.com/16641416/31868719-c575820e-b7d4-11e7-8fe1-de47dbe5ac3b.png)

改成以下方式就可以了。
       //。。。
        context.startActivity(intent);

        try {
            Thread.sleep(1000);
            exitIfForceUpdate(update);
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by yjfnypeu** [comment]
能说说这种问题是在什么版本上或者什么机型上出的问题么？估计是和机型有关系。

**Comment by yjfnypeu** [comment]
刚发了个小版本2.5.2，修复了此问题。[2.5.2](https://github.com/yjfnypeu/UpdatePlugin/releases/tag/2.5.2)

**Comment by luoximin1990** [comment]
华为p9 安卓7.0 ！！！

估计跟系统有关，杀手进程后立马安装uri为null导致报错的吧。

**Comment by yjfnypeu** [comment]
@anyway-whatever 这个问题刚解决了。你升级下2.6.0版本。
