### ISSUE TITLE
有关强制更新问题

### ISSUE THREAD

**Issue by Troll4it** [yjfnypeu/UpdatePlugin#44]
您好。。在你的demo中     

update.setForced(true);
                        // 是否显示忽略此次版本更新按钮
//                        update.setIgnore(object.optBoolean("ignore_able",false));
                        update.setIgnore(false);

我把自定义解析接口的这两个属性随意设置，在你的demo中点击启动更新并不能弹出更新窗口，请问这是什么原因造成的，谢谢

**Comment by yjfnypeu** [comment]
你可以在日志里添加tag过滤UpdatePluginLog。查看一下具体的更新日志。
