### ISSUE TITLE
demo中点击启动更新，下载完成后 我故意不安装，返回，再次点击启动更新   出问题了！！

### ISSUE THREAD

**Issue by DevXue** [yjfnypeu/UpdatePlugin#45]
demo中点击启动更新，下载完成后 我故意不安装，返回，再次点击启动更新   出问题了！！ 后台log提示: Already have a download task running
我的需求是， 我不点击安装  然而我再次请求  应该跳转到安装界面直接提示让我安装啊！  不应该在执行重新下载了对吧 ？  
请问是我操作有问题么？  还是这个库就是这样的？
![12](https://user-images.githubusercontent.com/9455329/32977841-a8be3150-cc70-11e7-8f96-da4d1c4828d6.png)

**Comment by yjfnypeu** [comment]
这是这个库用来避免同时启用多个下载任务的一种机制。防止由于同时使用多个任务下载同一个文件。出现问题。但是照你说的这样，如果是下载完成了的。正常来说重新启动更新。应该会跳过重启下载任务的。就不知道你是怎么使用的了。

**Comment by DevXue** [comment]
大神，  我就是用的你的demo  代码都没动！   我就是想知道，  如果APK下载完成后  跳到了安装界面，此时 我没有点击安装，而是点了取消了，  我又回到了dmeo中，  我又点击了启动更新，   然后我的想要的效果就是  这个APK已经下载好了对吧  那他就可以直接跳到安装界面让用户安装即可，  没必要重新下载了吧，  就是这么个需求，   我想知道 你的库是不是这么设计的呢？  有这个机制么 ？  如果下载了就不重新下载了 就让用户安装  安装好了在删除安装包啥的 下次有新版本在执行下载！这样的

**Comment by yjfnypeu** [comment]
有这个机制的。检查到有更新之后。在启动下载任务之前。是会进行判断是否此apk是已被下载好了的。如果是已经下载好了的就会跳过下载任务的。我本地运行测试是没这情况的。不知道你的是怎么回事。你可以跟一下Updater类的downUpdate方法。看看是哪块的问题？
