### ISSUE TITLE
设置强制更新，是否显示忽略此次版本更新按钮这个两个配置有问题

### ISSUE THREAD

**Issue by Troll4it** [yjfnypeu/UpdatePlugin#48]
![xbwbz2 p7h0od860n4 enh](https://user-images.githubusercontent.com/27883219/33705947-47e4bb18-db6d-11e7-9ca7-204970a695eb.png)
这是你demo中的代码。是否显示忽略此次版本更新按钮这个配置怎么设置都没有用，只要不设置强制更新就不能弹出版本更新的提示

**Comment by yjfnypeu** [comment]
设置了强制更新之后会默认关闭忽略版本更新。这个是正常的。

**Comment by Troll4it** [comment]
您好，很奇怪的事，  update.setForced(false)这个设置false不会弹出更新框，设置true就会。我把你的demo和文档都看了，就是没有找到原因，求解，谢谢

**Comment by yjfnypeu** [comment]
我估计你是之前在非强制更新的时候。开启了忽略版本更新。并且点击过忽略版本更新了。所以后续检查如果setForced(false)的话。都会判断为没有新版本更新。导致没有弹窗。具体的你可以看看框架提供的默认检查逻辑类：[DefaultChecker.java](https://github.com/yjfnypeu/UpdatePlugin/blob/master/updatepluginlib/src/main/java/org/lzh/framework/updatepluginlib/model/DefaultChecker.java) 验证一下是否是这原因

**Comment by Troll4it** [comment]
![z sl93r1h as ing2i_gd](https://user-images.githubusercontent.com/27883219/33826806-1a19a68a-dea1-11e7-905c-b3d5c679f62d.png)

我把那个检测类的一些数据给打印出来，没有显示我的忽略的版本信息

**Comment by yjfnypeu** [comment]
你可以使用UpdatePluginLog做日志过滤。可以帮助定位具体的问题

**Comment by Troll4it** [comment]
![711 p_0b g2al 73hcvvq1v](https://user-images.githubusercontent.com/27883219/33830351-cfee5caa-deae-11e7-907a-0189867d6f01.png)
有关 你的这个指导不太懂，是这样操作的吗？？谢谢

**Comment by yjfnypeu** [comment]
嗯。是的。你启动一次有问题的更新任务。然后看看这里的输出，可以帮助定位具体问题在哪
