### ISSUE TITLE
文档没看明白怎么用，是只能用GET方法？

### ISSUE THREAD

**Issue by andansky** [yjfnypeu/UpdatePlugin#5]
// 建议在Application中进行配置。
// UpdateConfig为全局配置。当在其他页面中。使用UpdateBuilder进行检查更新时。
// 对于没传的参数，会默认使用UpdateConfig中的全局配置
UpdateConfig.getConfig()
            // 必填：数据更新接口
            .url(url)
            // 必填：用于从数据更新接口获取的数据response中。解析出Update实例。以便框架内部处理
            .jsonParser(new UpdateParser() {
                @Override
                public Update parse(String response) {
                    // 此处根据上面url接口返回的数据response进行update类组装。
                    return update;
                }
            })
首先，我不知道这个的原理是怎样的，到底是app这版把版本号传去服务器，服务器比对还是服务器直接通过连接把版本号传来app，app自己比对。如果是直接返回的那response的格式是怎样的呢？理解能力有点差。。。。希望作者能耐心解释一下。谢谢

**Comment by yjfnypeu** [comment]
嗯，是通过你指定的url去访问服务器，服务器传回的数据就是回调中的response，你根据服务器返回的response数据来构造个UpdateBean对象。框架内部用来判断是否需要更新的。后面会写个详细的教程出来，最近离职正在找工作中。家里没电脑暂时改不了，见谅见谅

**Comment by sooner0493** [comment]
这文档确实看得我一头雾水。。。

**Comment by yjfnypeu** [comment]
@sooner0493 哪里没看懂

**Comment by yjfnypeu** [comment]
检查更新接口可以查看这个文档：

[配置：更新接口api](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E9%85%8D%E7%BD%AE%EF%BC%9A%E6%9B%B4%E6%96%B0%E6%8E%A5%E5%8F%A3api)

对于其他的可配置接口。可对比此流程进行了解：

[更新流程及配置](https://github.com/yjfnypeu/UpdatePlugin/wiki/%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E#%E6%9B%B4%E6%96%B0%E6%B5%81%E7%A8%8B%E5%8F%8A%E9%85%8D%E7%BD%AE)
