### ISSUE TITLE
Android7.0更新下载完成后闪退

### ISSUE THREAD

**Issue by winterfeel** [yjfnypeu/UpdatePlugin#50]
Android7.0更新下载完成后闪退，有时候也会提示“包解析错误”，网上查到可能是android7.0的文件读取权限问题，需要使用fileprovider什么的，低版本没有问题，希望作者尽快更新下，谢谢

测试设备：红米5Plus 安卓7.1.2
测试更新插件版本：2.6.0和2.7.0都试过，一样

**Comment by winterfeel** [comment]
然后再次打开还是提示更新的，点击更新，继续闪退。应该是打开apk路径权限问题，报的错好像和app没有关系，参考：
Unable to load resource 0x00000000 from pkg=com.android.systemui
                                       android.content.res.Resources$NotFoundException: Resource ID #0x0
                                           at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:201)
                                           at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:92)
                                           at android.content.res.Resources.getDrawable(Resources.java:788)

**Comment by yjfnypeu** [comment]
光看这个看不出来。看样子是resource id无效的问题。可以把详细错误日志截图发出来看看。个人估计可能是你定制的界面通知里面出的问题。

**Comment by winterfeel** [comment]
2.7.0版本
在Application里我写了配置：

> UpdateConfig.getConfig()
                .setUrl(Constant.CHECK_UPDATE+"?appid=1")
                .setUpdateParser(new UpdateParser() {
                    @Override
                    public Update parse(String response) {
                        try {
                            JSONObject obj = new JSONObject(response);
                            Update update = new Update();
                            update.setUpdateUrl(obj.getString("apk"));
                            update.setVersionCode(obj.getInt("versionCode"));
                            update.setVersionName(obj.getString("versionName"));
                            update.setUpdateContent(obj.getString("info"));
                            update.setForced(obj.getInt("force") == 1);
                            update.setIgnore(false);
                            return update;
                        } catch (JSONException e) {
                            e.printStackTrace();
                            Log.v("info", e.getMessage());
                            return null;
                        }
                    }
                });


然后在activity里写了：
>UpdateBuilder.create().setUpdateStrategy(new UpdateStrategy() {
            @Override
            public boolean isShowUpdateDialog(Update update) {
                // 有新更新直接展示
                return true;
            }
            @Override
            public boolean isAutoInstall() {
                return true;
            }
            @Override
            public boolean isShowDownloadDialog() {
                // 展示下载进度
                return true;
            }
        }).check();

其他什么也没改过，也测试了华为7.0+的系统，更新完安装的时候提示“包解析错误”。
然后AndroidStudio里面报错内容乱七八糟的不是app的报错是系统的好像。
麻烦你看下和这篇文字说的有关吗《Android 7.0解析包时出现问题 的解决方案（应用内更新）》http://blog.csdn.net/y505772146/article/details/55255344

**Comment by winterfeel** [comment]
刚刚测试发现isAutoInstall() 写false，不自动安装就不会闪退.....手动点击安装就可以，填写true才会出现

**Comment by yjfnypeu** [comment]
跟这个没关系，你这FileProvider的逻辑的框架内提供了个默认的contentprovider来实现。这个跟你上面贴的那部分日志没关系。我是说你贴一下你这块具体的错误日志，截图出来看看。不然不能定位问题。不过早期有朋友也遇到过类似解析包失败的问题，是v2签名的问题。你也可以搜索了解一下

**Comment by yjfnypeu** [comment]
而且我不太明白。你这到底是闪退还是包解析失败？

**Comment by winterfeel** [comment]
应用程序没有出错日志，log里只有系统的这个error日志。
选择isAutoInstall() 是true后，下载完成后直接闪退，然后也没有出错日志，只是系统的这个什么Unable to load resource 0x00000000 from pkg=com.android.systemui
在另一款华为机子中的情况是弹处安装界面了，但是安装界面显示 包解析错误。
签名我目前都只勾选了v1，没有采用v2。
目前我通过isAutoInstall 设为false来暂时解决这个问题，麻烦作者您了

**Comment by yjfnypeu** [comment]
闪退如果没日志的话。估计你的是使用的强制更新？强制更新的安装策略就是调起安装程序之后。强制关闭当前应用的。

**Comment by yjfnypeu** [comment]
isAutoInstall只是用来控制是否对下载完成后的近点进行界面通知显示的。这个跟你说的这问题应该没关系吧？你使用isAutoInstall之后。调起安装程序就能不出现包解析失败了？

**Comment by winterfeel** [comment]
是的。。。使用autoinstall true的时候，下载完当前app关闭了，然后也没有吊起安装程序。autoinstall false的时候吊起了安装程序，没有出错....我也不知道为啥，哈哈哈，主要是看不到错误日志

**Comment by yjfnypeu** [comment]
...这么扯？那你在DefaultInstallStrategy这个类中的install打个断点。看看有没啥数据变化？这个是默认的安装策略。调起安装程序就是在这里

**Comment by winterfeel** [comment]
哈哈大神实话说，我菜得很...断电也不会打哈哈，我再研究下，等有新发现了和你留言，谢谢大神

**Comment by yjfnypeu** [comment]
OK。你如果研究好了。希望你能在这里贴一下你的成果哈。我看看是不是可以更新到wiki中去。客气了

**Comment by iDoStudy** [comment]
@yjfnypeu @winterfeel @wuqi713 有解决方案喽，请看#58
