### ISSUE TITLE
App update with count notification

### ISSUE THREAD

**Issue by AhmerAfzal1** [yjfnypeu/UpdatePlugin#52]
First of all thanks for awesome library, I need help how I can show in app icon and in Setting Activity with Count Notification (Push Notification) associate with this library when new app update is available?

**Comment by yjfnypeu** [comment]
Uh. . .Sorry, I do not understand what this relationship with the Count Notification.

**Comment by yjfnypeu** [comment]
You can set a CheckCallback by UpdateBuilder to receive update status. and displayed in callback method hasUpdate.

**Comment by AhmerAfzal1** [comment]
Please feel free to send me a piece of code for it?

**Comment by yjfnypeu** [comment]
OK. 
```java
boolean hasUpdate;// store it in your data manager. and used in Setting Activity.

UpdateConfig.getConfig()
		...// your configurations
		.setCheckCallback(new CheckCallback(){
			...// other callbacks
			public void hasUpdate(Update update) {
				hasUpdate = true;
			}
			
			public void noUpdate() {
				hasUpdate = false;
			}
		})
		
```

**Comment by AhmerAfzal1** [comment]
Thanks you
