### ISSUE TITLE
部分机型，例：oppoR9s，报错：

### ISSUE THREAD

**Issue by zhaolei9527** [yjfnypeu/UpdatePlugin#53]
Unable to get provider org.lzh.framework.updatepluginlib.util.UpdateInstallProvider: java.lang.ClassNotFoundException: Didn't find class "org.lzh.framework.updatepluginlib.util.UpdateInstallProvider" on path: DexPathList

**Comment by yjfnypeu** [comment]
这种问题怀疑是multidex分包把这个Provider给分到次包中去了。你可以检查一些主dex中是不是没有这个类？
