### ISSUE TITLE
建议开放版本更新接口

### ISSUE THREAD

**Issue by skyCracks** [yjfnypeu/UpdatePlugin#54]
有的时候项目本身有网络请求库，且版本更新的接口不一定符合此库的Update数据格式，有的接口只取versionName做判断，没有使用versionCode,最后将setUpdateParser（）方法开放出来，便于使用项目本身接口获取数据组装Update

**Comment by yjfnypeu** [comment]
所有的这些全都是开放出来了的。。。建议仔细看看wiki配置说明。[更新配置说明](https://github.com/yjfnypeu/UpdatePlugin/wiki/Configurations-Explains)
