### ISSUE TITLE
从0.4版本看到现在越看越懵逼

### ISSUE THREAD

**Issue by Troll4it** [yjfnypeu/UpdatePlugin#55]
感觉方法越用越复杂，耦合性越来越强，2.5版本 的时候还可以传递自己传递版本更新的JSON字符串，现在都找不到方法，大佬，怎么解决

**Comment by yjfnypeu** [comment]
呃。因为JSON字符串很多人用不上。需要扩展的。可以直接继承Update类。解析返回你这个扩展类即可。在需要使用的地方。转回你自己的扩展类进行使用即可。
