### ISSUE TITLE
service 轮查升级异常

### ISSUE THREAD

**Issue by freedomDR** [yjfnypeu/UpdatePlugin#56]
您好，我在service里设置更新并启动，报的错误为**check update failed: cause by : null**, 有没有更详细的错误，或者说是哪里的问题

**Comment by yjfnypeu** [comment]
你可以在日志里翻翻。这种使用过程中出异常的。都有打印出来具体的堆栈信息的。

**Comment by freedomDR** [comment]
是**context**为空，我看你源代码，context是通过activity栈的最顶层获取，service也可以作为context吧

**Comment by yjfnypeu** [comment]
你的应用里没有Activity么？更新流程中有涉及到UI的操作。最好使用Activity的context。Service毕竟与Activity不一样。

**Comment by freedomDR** [comment]
开机service自启动来完成更新升级的

**Comment by yjfnypeu** [comment]
呃。。。那这种的话。有点问题。因为现在需要界面显示通知的。都必须是基于Activity的Context来进行界面创建的。所以开机自启用的Service是用不了的。这种情况我目前替你想了两种方案可以参考以下。

第一种：可以考虑开机自启时。启动一个透明的Activity页。启动之后再将此Activity放回后台。

第二种：对于这种开机自启进行更新升级的。全程要求不显示界面通知，这种默认配置一个更新策略就行。检查有更新自动下载。下载完成后自动调起安装。这种相对来说应该能更符合你这应用场景。

**Comment by freedomDR** [comment]
恩，可以，第二种可以，我是否还需要个自己再配置个更新数据检查器，重配一下context

**Comment by yjfnypeu** [comment]
照理说不需要。更新数据检查器跟这种逻辑没有关系。不进行界面显示。内部也就不会需要使用context了。你可以先试试。看看有没别的问题先

**Comment by yjfnypeu** [comment]
然后我觉得你这种后台更新。可以考虑使用UpdateBuilder的checkWithDaemon方法。进行后台自动轮询更新。这种方式可以在检查到不存在更新或者更新失败后。间隔一定时间之后自动重启更新任务。

**Comment by freedomDR** [comment]
恩， 我试一下。我更改了更新策略， **E/CheckNotifier--->: Activity was recycled or finished,dialog shown failed!**, 这是啥原因，已经设置没有弹出框了

**Comment by yjfnypeu** [comment]
这只是内部的一个日志。没影响。

**Comment by yjfnypeu** [comment]
刚想起。估计你这里还需要重新加个更新数据解析器。然后此处强制要求'强制更新'关闭。因为如果设置了强制更新。内部会自动替换强制更新特有的更新策略。这就会对你这块的逻辑造成影响。

**Comment by yjfnypeu** [comment]
刚发布了2.9.0版本。兼容了没有top activity实例时导致异常的问题。可以升级体验一下。

**Comment by freedomDR** [comment]
估计用context的地方很多，还是稍微有一些问题，我试试能不能调用AvtivityManage 的 registSelf注册一下

**Comment by yjfnypeu** [comment]
换2.9.0还是有context问题？那现在是啥问题呢？

**Comment by freedomDR** [comment]
DefaultFileCreator.getCacheDir 的问题，用context的地方很多

**Comment by yjfnypeu** [comment]
这个不应该为null才对啊？这种是使用的Application的context。而且这个application的context是应用启动时，加载ContentProvider时自动注册的。你现在application的context也为null么？

**Comment by freedomDR** [comment]
现在application的context不为空，service本身也是个context。还不知道咋回事，我试试弄个空的acticity

**Comment by yjfnypeu** [comment]
那现在具体是有什么问题呢？看不出你这是啥问题了。。。

**Comment by freedomDR** [comment]
已用空的activity解决，谢谢，添加个license吧
