### ISSUE TITLE
三星galaxy note8 强制更新 安装闪退

### ISSUE THREAD

**Issue by situ91** [yjfnypeu/UpdatePlugin#57]
强制更新时安装会强杀进程，三星galaxy note8 确定安装界面没有完全出来就闪退掉了。
解决：暂时去掉强制更新时强杀进程。//注释 DefaultInstallStrategy 的exitIfForceUpdate

**Comment by yjfnypeu** [comment]
这是故意这样设计的。如果需要不强杀进程。可以考虑copy一份默认的安装策略进行修改后。添加定制使用。可以参考下方链接进行定制。

[更新安装策略定制说明](https://github.com/yjfnypeu/UpdatePlugin/wiki/InstallStrategy)

这样的设计是因为app无法接收安装程序的安装状态。避免用户调起安装程序后又取消安装。导致跳过了此次强制更新检查逻辑。这样强制就没意义了

**Comment by situ91** [comment]
我现在就是模仿DefaultInstallStrategy去定制，去掉强杀，因为强杀在有些有机型（三星galaxy note8    android 7.0）连安装界面都显示不出来就杀掉了。并强制更新下，更新提示窗口点击升级后不dismiss，用户就跳不过强制更新逻辑了

**Comment by yjfnypeu** [comment]
你是使用的最新包么？之前也有遇到过类似的问题。新版已经解决。建议使用最新版本进行测试，或者你有找到安装界面显示不出来的原因没？

**Comment by situ91** [comment]
我是使用2.8.0版本的了，有看到安装界面出的来动画 ， 出到一半就闪退掉了。小米6 android 7.0 并没有这个问题。我也还没有查到具体原因。

**Comment by yjfnypeu** [comment]
刚修改了强制更新策略。现在不使用杀死进程的方式了。改为强制更新时。展示的dialog点击进行安装时，不自动消失的方案了，这种应该可接受度要高点。可以参考2.9.0的更新日志。

[release 2.9.0](https://github.com/yjfnypeu/UpdatePlugin/releases/tag/2.9.0)
