### ISSUE TITLE
WIFI环境静默下载时，用户手动检测更新失效

### ISSUE THREAD

**Issue by lijunhuayc** [yjfnypeu/UpdatePlugin#59]
使用场景：
     WIFI环境一般，启动APP检测到更新，后台静默下载（默认WifiFirstStrategy策略）。

` mHandler.postDelayed(() ->
    UpdateBuilder
            .create()
            .setUpdateStrategy(new WifiFirstStrategy())
            .check(), 3000);
`

此时用户进入版本检测页面手动点击检测版本，会失效。

`UpdateBuilder.create()
        .setUpdateStrategy(new UpdateStrategy() {
            @Override
            public boolean isShowUpdateDialog(Update update) {
                return true;
            }

            @Override
            public boolean isAutoInstall() {
                return false;
            }

            @Override
            public boolean isShowDownloadDialog() {
                return true;
            }
        })
        .setCheckCallback(new CheckCallback() {
            @Override
            public void onCheckStart() {
                mHandler.post(() -> {
                    showDialog();
                    setMsg("版本检测中");
                });
            }

            @Override
            public void hasUpdate(Update update) {
                stopDialog();
            }

            @Override
            public void noUpdate() {
                stopDialog();
                MyToast.showToast("当前已是最新版");
            }

            @Override
            public void onCheckError(Throwable t) {
            }

            @Override
            public void onUserCancel() {
            }

            @Override
            public void onCheckIgnore(Update update) {
            }
        })
        .check();`

原因分析：
        WIFI网络差，启动后静默下载未未完成，此时用户手动检测到更新，再一次触发DownloadWorker.run，其中checkDuplicateDownload方法检测到存在相同任务正在执行。直接抛出异常，任务执行失败。由于框架采用的“行为分离”的方式，此时手动更新的执行的是一个全新的UpdateBuilder/UpdateConfig。

解决方案思考：
       由于当前框架并无暂停/停止任务执行的策略，一旦执行DownloadWorker，使用者不能主动终止任务。所以可以考虑将用户常用回调设计为List<CallBack> 形式，在检测到存在同一个任务正在执行时，终止当前DownloadWorker的同时，将当前DownloadWorker的UpdateConfig中的用户回调给代理到上一个任务中去，这样既不影响原先任务的正常执行，也能保证当前的检测能接收到任务执行的各种回调。这里考虑到安装策略的问题，前面说了用户一旦开始下载，不能主动终止下载任务，所以可以考虑，策略方面直接覆盖，回调方面使用List（其他页面可能也需要上一个任务的回调通知，而策略取决于用户的操作行为）。

**Comment by yjfnypeu** [comment]
这问题在新版本中已解决修复。去掉了重复任务检测，采用任务分离模式来进行更新。

使用checkForDaemon启动后台更新：

```java
UpdateBuilder.create()
    .checkWithDaemon(retryTime);
```

后台更新任务会在检测到无更新或者更新失败后，自动延迟一定retryTime时间后，重启更新任务。

在设置也点击更新时，使用前台更新：

```java
UpdateBuilder.create()
    .check();
```

**Comment by lijunhuayc** [comment]
补充一个问题，前后台下载完成提示安装的Dialog的title貌似都叫“免下载安装”，不太合适，用户明明是在前台等待progress下载完成的。
解决方案考虑：
   如果实在要使用“免下载安装”文字，则可以根据策略来显示不同的title，否则去掉title的显示或者统一显示为“安装”/“提示”/“更新”/“安装提示”等等...

**Comment by lijunhuayc** [comment]
补充2：
      md5校验环节可以考虑，在DefaultFileChecker.checkByMD5中将两个md5使用equalsIgnoreCase比较，可以减少使用者在MD5大小写不统一的情况下安装失败却要一步一步的排查的过程。

**Comment by yjfnypeu** [comment]
已更新发布，[2.9.1](https://github.com/yjfnypeu/UpdatePlugin/releases/tag/2.9.1)版本
