### ISSUE TITLE
强制更新的状态下为什么我按下返回键，更新对话框就消失了。。。然后又能进入应用了。

### ISSUE THREAD

**Issue by andansky** [yjfnypeu/UpdatePlugin#6]
强制更新的状态下为什么我按下返回键，更新对话框就消失了。。。然后又能进入应用了。强制更新不是应该不更新就进不了应用的吗。。。。

**Comment by yjfnypeu** [comment]
嗯，这算是个bug，会在后期修复的。

**Comment by andansky** [comment]
还有为什么我点了立即更新之后啥反应都没有呢？就对话框消失了而已。下载地址我填了这个：http://119.29.91.129:8080/app.apk
我用的是这个更新策略：
UpdateBuilder.create()
    .strategy(new UpdateStrategy() {
        @Override
        public boolean isShowUpdateDialog(Update update) {
            // 有新更新直接展示
            return true;
        }

```
    @Override
    public boolean isAutoInstall() {
        return false;
    }

    @Override
    public boolean isShowInstallDialog() {
        // 展示下载完成安装提示
        return true;
    }

    @Override
    public boolean isShowDownloadDialog() {
        // 展示下载进度
        return true;
    }
})
.check(MainActivity.this);
```

有一句错误提示：
Failed to ensure directory: /storage/sdcard1/Android/data/com.xinji.jugongyouyue/cache
这个sdcard1是外内存卡的路径吧？我手机没有内存卡都是sdcard0的呢

**Comment by yjfnypeu** [comment]
这不清楚呢。可以的话可以加我QQ细聊。470368500，或者我加你

**Comment by yjfnypeu** [comment]
这不清楚呢。可以的话可以加我QQ细聊。470368500，或者我加你

**Comment by andansky** [comment]
加不了你呢。你的设问题了。我的QQ是664996919

**Comment by xiaolongyuan** [comment]
+1

**Comment by 99api** [comment]
您好，同样有问题想请教，加不了您，我的qq是 178791359

**Comment by hanxiaozhe** [comment]
这些问题都还没有解决么？在最新版本中

**Comment by yjfnypeu** [comment]
都是解决的了。忘了更新这个issue了。抱歉
