### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by hegelsu** [yjfnypeu/UpdatePlugin#61]
1. 由于InstallNotifier的create要返回一个Dialog，但我自定义时由于用的弹出框组件并不是Dialog类型，所以这里就不知道如何是好了
2. 现在我是通过setDownloadCallback来自己做进度条的展示，因为是强制安装，所以在下载完成之后我是希望直接到安装的界面，不希望中间还提示一个框来让用户点，不知道这个流程要怎么设置？

**Comment by yjfnypeu** [comment]
你可以参考下demo中提供的定制通知栏进度条的代码。

**Comment by fandazeng** [comment]
产品要求在下载完成之后我是希望直接到安装的界面，不希望中间还提示一个框来让用户点，这个流程有设置的方法吗？

**Comment by Vicent9920** [comment]
请查看`Wiki`，更新策略支持更新完成后自动安装的
