### ISSUE TITLE
demo中的【通知栏进行进度条显示更新】无效

### ISSUE THREAD

**Issue by protectedMan** [yjfnypeu/UpdatePlugin#63]

**Comment by protectedMan** [comment]
无通知消息/

**Comment by yjfnypeu** [comment]
建议使用UpdatePluginLog进行一下日志过滤查看，看看是否有在正常下载，如果下载正常。那就可以再检查一下你的app是否开启的通知栏显示。

**Comment by protectedMan** [comment]
通知是允许通知的，demo中别的通知都可以。  然后下载也是正常下载，正常提示安装。 多款手机都出现这种情况。

**Comment by yjfnypeu** [comment]
emmm。。。这种情况我这边就没法帮你判断解决了，可以具体深入查看一下你们这种情况下的日志(主要是系统通知方面的日志)，demo中的通知都是简单写的，是可能会出现一些兼容性问题。同时如果找到具体原因了，也希望在这里更新一下，我也好修改进demo代码中。谢谢了~

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/38233150-20be8a60-374c-11e8-809a-cb1b8b36c69e.png)
这个断点都不走的。。

**Comment by yjfnypeu** [comment]
emmm... 这就比较清晰了。这里不走说明你的更新策略里面配置的，就是不显示下载进度的。你可以先查看一下这里的[更新显示策略](https://github.com/yjfnypeu/UpdatePlugin/wiki/UpdateStrategy)，框架是依赖此策略类来进行显示判断的。

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/38233394-0009278e-374d-11e8-89f1-b3a59a3d4a8a.png)
这行断点走了

**Comment by yjfnypeu** [comment]
你把demo里面的'使用所有通知全部显示的策略'这一项勾选上，就能展示出来了。

**Comment by protectedMan** [comment]
还是不行

**Comment by yjfnypeu** [comment]
你清理一下数据再试，应该是之前已经APK下载好了，所以后期要求更新时，因为已经下载好了。就不会再次重新下载。框架内有这种策略的。

**Comment by protectedMan** [comment]
这个考虑到了，网速都在跳动但是没有进度通知。

**Comment by yjfnypeu** [comment]
那你在DefaultDownloadCallback的getInnerCB()方法打断点看看吧，这里就是控制展示下载进度条的地方。

**Comment by ningsk** [comment]
因为android8.0以上通知需要添加channel信息，所以
修改demo里面NotificationDownloadCreator方法即可。
```java
 private static final String CHANNEL_ID = "app_update_id";
  private static final CharSequence CHANNEL_NAME = "app_update_channel";
NotificationCB (Activity activity) {
            this.manager = (NotificationManager) activity.getSystemService(Context.NOTIFICATION_SERVICE);

            id = Math.abs(UUID.randomUUID().hashCode());
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
                NotificationChannel channel = new NotificationChannel(CHANNEL_ID, CHANNEL_NAME, NotificationManager.IMPORTANCE_HIGH);
                channel.enableVibration(false);
                channel.enableLights(false);

                manager.createNotificationChannel(channel);
            }


            builder = new NotificationCompat.Builder(activity, CHANNEL_ID);

            builder.setProgress(100, 0, false)
                    .setSmallIcon(activity.getApplicationInfo().icon)

                    .setAutoCancel(false)
                    .setContentText("下载中...")
                    .setContentText("版本更新")
                    .build();

        }
```
