### ISSUE TITLE
强制更新时，更新策略被覆盖。

### ISSUE THREAD

**Issue by protectedMan** [yjfnypeu/UpdatePlugin#65]
建议增加两套更新策略，强制更新时的更新策略和非强制更新时的更新策略

目前是下面这种，限制太多。

// 当需要进行强制更新时。覆盖替换更新策略，且关闭忽略功能
        if (update.isForced()) {
            update.setIgnore(false);
            builder.setUpdateStrategy(new ForcedUpdateStrategy(builder.getUpdateStrategy()));
        }

**Comment by yjfnypeu** [comment]
目前的这个强制更新策略是为了打开应用安装之前的通知。因为需要保证不被用户手动取消安装的操作导致强制更新失效。不知道你们是个什么样的逻辑需要修改这块逻辑？不过如果真需要特殊的强制更新策略的话。建议扩展Update实体类。添加一个额外的属性去进行具体控制。
