### ISSUE TITLE
当前有新版本需要更新只能用Dialog进行提示

### ISSUE THREAD

**Issue by protectedMan** [yjfnypeu/UpdatePlugin#66]
有没有接口可以配置使用其他组件比如DialogFragment进行弹出提示。

**Comment by yjfnypeu** [comment]
框架并不规定必须用Dialog进行提示的，需要使用别的方式进行展示，定制的通知器(XXXNotifier)不返回具体的Dialog即可，可以参考app示例代码中的相关定制(通知栏显示方式).

**Comment by protectedMan** [comment]
好的，懂了！
