### ISSUE TITLE
小米8.0系统下载完安装提示解析失败

### ISSUE THREAD

**Issue by Marx-Hong** [yjfnypeu/UpdatePlugin#67]
测试用的机子是小米MIX2s，其他途径下载安装正常，使用框架更新下载后安装提示解析包错误

**Comment by yjfnypeu** [comment]
你可以从一下几个方面来进行排查：
1. 服务器提供的apk是否与其他途径(应用市场)的apk是否一致。检查一下服务器apk是否有效
2. 找到本地下载的apk文件，直接安装测试是否成功
3. 之前也经常性有出现类似问题，是v2签名导致的问题。将v2签名去掉试试

**Comment by Marx-Hong** [comment]
好的，谢谢

**Comment by ghost** [comment]
你好。问题解决了吗？ 
也出现这个问题，下载的apk拉出来安装正常。就是下载完安装提示解析失败。 
模拟器测试正常。


手机型号： MIX 2
MIUI版本： MIUI 9.6
Android版本： 8.0.0
