### ISSUE TITLE
建议把Dialog改成Activity

### ISSUE THREAD

**Issue by chenwulue** [yjfnypeu/UpdatePlugin#7]
建议把Dialog改成一个透明的Activity+Dialog（或者简单布局），因为现在的情况是无法使用context，如果改成用Activity的话，是可以通过getApplicationContext来启动的，可以避免检查过程中关掉该页面导致的空指针

**Comment by yjfnypeu** [comment]
使用ApplicationContext来启动页面不推荐。我明白你的意思。你是在检查过程中关闭了页面。导致DialogCreator中方法的activity参数为空。这个就是这样设计的。因为框架内部使用的弱引用保存你引进的Activity.所以你关闭了页面后会回收此Activity。这种情况下。需要你自己重新指定使用的Activity.比如我们会自己维护一个Activity栈。这样当回调的时候。我可以使用最顶层的Activity来启动Dialog。
