### ISSUE TITLE
需求：在主动更新的时候需要弹出toast提示，而在后台更新不需要提示

### ISSUE THREAD

**Issue by tdxtxt** [yjfnypeu/UpdatePlugin#73]
比如 UpdateBuilder.create().check()，在check方法中传入回调，在回调中得到网络请求数据，以供开发者自己处理是否弹出toast

感谢作者，个人觉得这框架是网上设计的最好的一个吧，扩展性真的很强！！！

**Comment by yjfnypeu** [comment]
多谢你的肯定

这个需求很容易解决，并不需要再单独进行框架层的修改。只需要分别对`主动更新`与`后台更新`所使用的`UpdateBuilder`实例。配置不同的callback即可。

**主动更新**

```
UpdateBuilder.create()
    .setDownloadCallback(toastCallback)
    .setCheckCallback(toastCallback)
    .check()
```

**后台更新**

```
UpdateBuilder.create().checkWithDaemon()
```

**Comment by tdxtxt** [comment]
明白了，灵活性强
