### ISSUE TITLE
断点下载问题

### ISSUE THREAD

**Issue by tdxtxt** [yjfnypeu/UpdatePlugin#74]
这个问题并非100%浮现

问题描述： 在更新下载途中，终端网络，强制杀死应用程序 ，然后打开网络，再次进入应用进行断点下载，此时会出现无法下载的问题。

测试模拟器：genymotion：Custom Phone - 6.0.0（好像只有这个模拟器出现问题）

检查原因：由于在DownloadWrker中
private static Map<DownloadWorker, File> downloading = new HashMap<>();
静态变量导致的，去掉static就可以了，很奇怪

**Comment by yjfnypeu** [comment]
你这无法下载的具体表现是啥？有没错误日志？

而且建议不要使用模拟器进行测试。曾经我也发现过类似的问题：

使用部分模拟器进行测试时。会在特定场景下，锁死在下载任务的 **urlConnect.connect()** 建立网络连接处。不知道你遇到的是不是也是此问题。如果是的话就不用考虑了。这种算是模拟器的问题。

**Comment by tdxtxt** [comment]
具体表现，就是没有下载进度
日志：You can not download the same file using multiple download tasks simultaneously，the file path is %s

**Comment by tdxtxt** [comment]
并且这个模拟器还存在一个问题
public void launchCheck(UpdateBuilder builder) {
        // 定义一个默认的检查更新回调监听。用于接收api检查更新任务所发出的通知。并链接后续流程。
        DefaultCheckCallback checkCB = new DefaultCheckCallback();
        checkCB.setBuilder(builder);
        checkCB.onCheckStart();

        CheckWorker checkWorker = null;
        try {
            checkWorker = builder.getCheckWorker().newInstance();
        } catch (Exception e) {
            throw new RuntimeException(String.format(
                    "Could not create instance for %s", builder.getCheckWorker().getCanonicalName()
            ), e);
        }
        checkWorker.setBuilder(builder);
        checkWorker.setCheckCB(checkCB);
        builder.getConfig().getExecutor().execute(checkWorker);
    }
这个方法中的线程池的2个线程一直处于active状态，队列中的任务无法执行，估计是在下载过程中突然中断导致的。

**Comment by yjfnypeu** [comment]
嗯。说明你遇到的问题应该就是我上面说的那种问题。不使用模拟器就好了。
