### ISSUE TITLE
checkByPM()

### ISSUE THREAD

**Issue by junchenChow** [yjfnypeu/UpdatePlugin#81]
private void checkByPM() {
        Context context = ActivityManager.get().getApplicationContext();
        PackageManager packageManager = context.getPackageManager();
        PackageInfo packageInfo = packageManager.getPackageArchiveInfo(file.getAbsolutePath(), PackageManager.GET_ACTIVITIES);
        if (packageInfo.versionCode != update.getVersionCode()) {
            throw new IllegalStateException(
                    String.format("The version code not matched between apk and update entity. apk is %s but update is %s",
                            packageInfo.versionCode, update.getVersionCode())
            );
        }
    }

我versionCode = 4 ， Update实体类是5，不能更新？没看懂你这段代码。。。

**Comment by yjfnypeu** [comment]
这里是把你下载下来的apk的versionCode跟Update实体类中的versionCode进行比对，这两个必须是一致的

**Comment by junchenChow** [comment]
我把这段注释了。如果强行不一致 你后面的处理流程是怎样的呢~

**Comment by yjfnypeu** [comment]
不会对后续流程造成影响。这只是对apk进行安全性检查的。
