### ISSUE TITLE
强制更新下载app失败后，点击对话框的“退出”按钮，应用奔溃。

### ISSUE THREAD

**Issue by bingdiao** [yjfnypeu/UpdatePlugin#83]
你好，强制更新下载app途中，如果网络中断，弹出了框架自带的对话框，显示的是要么“退出”，要么“重下”，点击“退出”按钮的话，APP就奔溃了。能帮忙看一下吗？

**Comment by yjfnypeu** [comment]
崩溃日志是啥？而且你这应该不是框架自带的对话框。框架自带的是没有重下按钮的。

**Comment by bingdiao** [comment]
对话框标题为：下载apk失败
对话框内容：是否重新下载？
有两个按钮分别为“退出”和“确定”，点击“退出”按钮，在一台Android7.1.1的锤子手机上就崩溃了。

崩溃日志没有看到啊。。。只有看到打印下面的出来：
11-05 18:39:19.157 17774-17774/zxm.android.app I/IgnoreTouchEvent: ignoreinputaction = false, x = 177.83534 , y = 1124.4143, pkg = zxm.android.app, wid = 35.0, slopex = 35.0, slopy = 24.0, timeout = 200.0
11-05 18:39:19.364 17774-17774/zxm.android.app I/IgnoreTouchEvent: ignore up event : x = 177.83534, ignore = false, ignoreUp = false, pkg = zxm.android.app
11-05 18:39:19.369 17774-17774/zxm.android.app I/art: System.exit called, status: 0

**Comment by yjfnypeu** [comment]
应该是杀死进程后应用自动重启的锅。你把版本号改为36c6fc9925试试。这版本我调了下退出逻辑，如果测试OK再给我说说。我再发正式版

**Comment by bingdiao** [comment]
大侠，36c6fc9925这版问题解决了，你发布正式版吧，感谢感谢^_^

**Comment by yjfnypeu** [comment]
好的。已经发布3.1.2。你用这个版本吧
