### ISSUE TITLE
忽略此版本相关问题

### ISSUE THREAD

**Issue by renygit** [yjfnypeu/UpdatePlugin#86]
点击忽略此版本后，完全退出app后再次打开，还是会弹出有更新，是怎么回事，打印了日志，没退出时是把版本号写入了的，这句UpdatePreference.saveIgnoreVersion(update.getVersionCode());没问题，重启后为什么没有了？写入的版本号没了，又弹出了版本更新。。。Set<String> ignoreVersions = UpdatePreference.getIgnoreVersions();
                        for (String str : ignoreVersions) {
                            打印str
                        }

**Comment by yjfnypeu** [comment]
首先，写入的版本号没了是啥意思？项目中是否自己定制了更新检查器`UpdateChecker`？默认的检查器类是`DefaultUpdateChecker`类。如果没自己定制可以到这里去打断点调试跟踪一下。

**Comment by renygit** [comment]
就是说退出前调用一下
Set ignoreVersions = UpdatePreference.getIgnoreVersions();
for (String str : ignoreVersions) {
打印str
}

重启再次调用，比如刚开始打印了版本号50， 重启就没有这个版本号了，没有定制更新检查器UpdateChecker

**Comment by yjfnypeu** [comment]
你意思是退出前版本号正确存入SP中了但是重启进入后，从sp中取出来数据就没这个版本号了？

**Comment by renygit** [comment]
> 你意思是退出前版本号正确存入SP中了但是重启进入后，从sp中取出来数据就没这个版本号了？

是的，我没有写清除SP的代码，定制的有setDownloadNotifier、setUpdateStrategy、setInstallNotifier、setCheckNotifier、setFileCreator

我本身安装的版本号是46，首次启动检查更新后，我点击取消，然后我打印出忽略列表中有46这个版本（我没有点击忽略就有这个号了），然后再次触发一下检查更新，我点击忽略，然后我打印出忽略列表中有46、50这两个版本，嗯，如果一直有这两个也没问题，我完全退出APP，再次打开后，又会弹出提示更新，我点取消，打印忽略列表，有46，没有50。就是这样

**Comment by renygit** [comment]
刚刚写了个Demo，可以重现这个问题[链接地址](https://github.com/renygit/TestUpdate)
机型：HUAWEI Mate 20    android 9.0.0

**Comment by yjfnypeu** [comment]
我这测试使用是正常的。不过我这没你这机型。是随便找的测试机，建议你可以结合https://github.com/amitshekhariitbhu/Android-Debug-Database 这个库动态的追踪SP数据进行查看。我这也没别的办法了。

**Comment by renygit** [comment]
> 我这测试使用是正常的。不过我这没你这机型。是随便找的测试机，建议你可以结合https://github.com/amitshekhariitbhu/Android-Debug-Database 这个库动态的追踪SP数据进行查看。我这也没别的办法了。

好吧，可能是高版本上有什么新特性吧⊙﹏⊙
对了，我不定制setDownloadNotifier、setUpdateStrategy、setInstallNotifier、setCheckNotifier、setFileCreator时是对的哦，就是把Demo中的这些定制取消就没问题了

**Comment by yjfnypeu** [comment]
你试试你这手机使用`Set<String>`格式进行SP存储试试呢？一般来说这种格式存储很少用。不知道是不是跟这个格式有关系。

**Comment by yjfnypeu** [comment]
你定制的InstallNotifier和CheckNotifier点击忽略此版本的时候都是调用的基类给提供的`sendUserIgnore`方法么？忽略版本更新逻辑就是在这两个Notifier的`sendUserIgnore`方法中将对应的`versionCode`存入SP。然后默认的更新检查器`DefaultUpdateChecker`中读取所有忽略列表进行判断。只要这部分逻辑没动。那不应该有问题的。

**Comment by renygit** [comment]
> 你定制的InstallNotifier和CheckNotifier点击忽略此版本的时候都是调用的基类给提供的`sendUserIgnore`方法么？忽略版本更新逻辑就是在这两个Notifier的`sendUserIgnore`方法中将对应的`versionCode`存入SP。然后默认的更新检查器`DefaultUpdateChecker`中读取所有忽略列表进行判断。只要这部分逻辑没动。那不应该有问题的。

我不知道该怎么说了，今天手机重启后没问题了，我代码没动过，这不得不说是手机的问题。很尴尬，这种异常居然可以重启搞定。。。

**Comment by renygit** [comment]
谢谢大佬回答我，感谢了#^_^#

**Comment by yjfnypeu** [comment]
好吧。。。搞定了就好。哈哈

**Comment by pengbs** [comment]
这个Set<String>确实会有问题，saveIgnoreVersion像下面这样改下就没问题了:
Set<String> ignoreVersions = new HashSet<>(getIgnoreVersions());
