### ISSUE TITLE
获取app版本号为null问题

### ISSUE THREAD

**Issue by waltkong** [yjfnypeu/UpdatePlugin#88]
在最新的版本包括demo如果是使用你的连接就可以实现下载，但是如果将md5设置为空实现app版本检测更新就会报出获取app的versionCode为null导致不能下载更新。

**Comment by yjfnypeu** [comment]
嗯。这个是下载的文件有问题。因为当不配置md5的时候。会用PackageManager去解析下载的apk，然后会用解析出来的数据去跟你Update中配置的versioncode进行匹配。这是做的安全过滤。你这问题就是这里解析apk的时候发生了问题。apk无效导致的。建议检查一下你们的apk。

**Comment by waltkong** [comment]
恩，刚刚要给你说，对不起是我的操作失误，给的下载连接不对，连接是一个打开网页的下载连接，

**Comment by yjfnypeu** [comment]
好的。解决了就好~

**Comment by waltkong** [comment]
谢谢了
