### ISSUE TITLE
每次下载完成之后提示下载APK失败，是否重新下载。

### ISSUE THREAD

**Issue by zhaoxiuyu** [yjfnypeu/UpdatePlugin#89]
UpdatePluginLog: Download task has occurs error: The version code not matched between apk and update entity. apk is 11 but update is 0
 java.lang.IllegalStateException: The version code not matched between apk and update entity. apk is 11 but update is 0

**Comment by zhaoxiuyu** [comment]
服务器上的版本是1.1， 手机上的版本是1.0.
我是实现了UpdateChecker这个类，判断两个VersionName的大小，来决定返回布尔值的。

**Comment by yjfnypeu** [comment]
服务器的apk的versioncode需要与update中的versioncode一致。

**Comment by zhaoxiuyu** [comment]
每次更新版本 versioncode 和 VersionName 都会更改， 不一样的。而且更新接口也只会返回VersionName 。
如何规避这个验证呢

**Comment by yjfnypeu** [comment]
你们更新接口不返回versioncode的么？那意思你们应用不需要进行apk有效性安全验证。那么你可以自己定制个FileChecker。不进行验证即可

**Comment by zhaoxiuyu** [comment]
多谢
